// <auto-generated />
using System;
using LojaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LojaApi.src.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701200448_AddPagamentoAgendamento")]
    partial class AddPagamentoAgendamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LojaApi.Models.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<int>("DuracaoMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_min");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_servico");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean")
                        .HasColumnName("pago");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("p_k_agendamentos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("i_x_agendamentos_cliente_id");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_agendamentos_loja_id");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("i_x_agendamentos_servico_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("i_x_agendamentos_venda_id");

                    b.ToTable("agendamentos");
                });

            modelBuilder.Entity("LojaApi.Models.CampoExtraLoja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chave");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<string>("Opcoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("opcoes");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("p_k_campos_extras_loja");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_campos_extras_loja_loja_id");

                    b.ToTable("campos_extras_loja");
                });

            modelBuilder.Entity("LojaApi.Models.CampoExtraPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chave");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<string>("Opcoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("opcoes");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("PerfilLojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_loja_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("p_k_campos_extras_perfil");

                    b.HasIndex("PerfilLojaId")
                        .HasDatabaseName("i_x_campos_extras_perfil_perfil_loja_id");

                    b.ToTable("campos_extras_perfil");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13000000-0000-0000-0000-000000000001"),
                            Chave = "tamanho",
                            Label = "Tamanho",
                            Obrigatorio = true,
                            Opcoes = "PP,P,M,G,GG,XG",
                            Ordem = 0,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Tipo = "lista"
                        },
                        new
                        {
                            Id = new Guid("13000000-0000-0000-0000-000000000002"),
                            Chave = "cor",
                            Label = "Cor",
                            Obrigatorio = false,
                            Ordem = 1,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Tipo = "texto"
                        },
                        new
                        {
                            Id = new Guid("15000000-0000-0000-0000-000000000001"),
                            Chave = "numero",
                            Label = "Número",
                            Obrigatorio = true,
                            Opcoes = "33,34,35,36,37,38,39,40,41,42,43,44,45",
                            Ordem = 0,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Tipo = "lista"
                        },
                        new
                        {
                            Id = new Guid("15000000-0000-0000-0000-000000000002"),
                            Chave = "cor",
                            Label = "Cor",
                            Obrigatorio = false,
                            Ordem = 1,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Tipo = "texto"
                        });
                });

            modelBuilder.Entity("LojaApi.Models.CategoriaLoja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("TamanhosPersonalizados")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tamanhos_personalizados");

                    b.Property<string>("TipoTamanho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_tamanho");

                    b.Property<bool>("UsaCor")
                        .HasColumnType("boolean")
                        .HasColumnName("usa_cor");

                    b.Property<bool>("UsaTamanho")
                        .HasColumnType("boolean")
                        .HasColumnName("usa_tamanho");

                    b.HasKey("Id")
                        .HasName("p_k_categorias_loja");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_categorias_loja_loja_id");

                    b.ToTable("categorias_loja");
                });

            modelBuilder.Entity("LojaApi.Models.CategoriaPerfilLoja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("PerfilLojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_loja_id");

                    b.Property<string>("TipoTamanho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_tamanho");

                    b.HasKey("Id")
                        .HasName("p_k_categorias_perfil_loja");

                    b.HasIndex("PerfilLojaId")
                        .HasDatabaseName("i_x_categorias_perfil_loja_perfil_loja_id");

                    b.ToTable("categorias_perfil_loja");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000001"),
                            Nome = "Semi Joias",
                            Ordem = 0,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000002"),
                            Nome = "Maquiagem",
                            Ordem = 1,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000003"),
                            Nome = "Acessórios",
                            Ordem = 2,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000004"),
                            Nome = "Outro",
                            Ordem = 3,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000001"),
                            Nome = "Camiseta",
                            Ordem = 0,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000002"),
                            Nome = "Calça Jeans",
                            Ordem = 1,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TipoTamanho = "numero"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000003"),
                            Nome = "Vestido",
                            Ordem = 2,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000004"),
                            Nome = "Bermuda",
                            Ordem = 3,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TipoTamanho = "numero"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000005"),
                            Nome = "Blusa",
                            Ordem = 4,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000006"),
                            Nome = "Casaco",
                            Ordem = 5,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000007"),
                            Nome = "Outro",
                            Ordem = 6,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000001"),
                            Nome = "Tênis",
                            Ordem = 0,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000002"),
                            Nome = "Sandália",
                            Ordem = 1,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000003"),
                            Nome = "Bota",
                            Ordem = 2,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000004"),
                            Nome = "Sapato",
                            Ordem = 3,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000005"),
                            Nome = "Chinelo",
                            Ordem = 4,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("16000000-0000-0000-0000-000000000001"),
                            Nome = "Ração",
                            Ordem = 0,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("16000000-0000-0000-0000-000000000002"),
                            Nome = "Petiscos",
                            Ordem = 1,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("16000000-0000-0000-0000-000000000003"),
                            Nome = "Brinquedos",
                            Ordem = 2,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("16000000-0000-0000-0000-000000000004"),
                            Nome = "Higiene",
                            Ordem = 3,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("16000000-0000-0000-0000-000000000005"),
                            Nome = "Acessórios",
                            Ordem = 4,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("16000000-0000-0000-0000-000000000006"),
                            Nome = "Medicamentos",
                            Ordem = 5,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("17000000-0000-0000-0000-000000000001"),
                            Nome = "Bebidas",
                            Ordem = 0,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("17000000-0000-0000-0000-000000000002"),
                            Nome = "Salgados",
                            Ordem = 1,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("17000000-0000-0000-0000-000000000003"),
                            Nome = "Doces",
                            Ordem = 2,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("17000000-0000-0000-0000-000000000004"),
                            Nome = "Cigarros",
                            Ordem = 3,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("17000000-0000-0000-0000-000000000005"),
                            Nome = "Higiene",
                            Ordem = 4,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("17000000-0000-0000-0000-000000000006"),
                            Nome = "Limpeza",
                            Ordem = 5,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("17000000-0000-0000-0000-000000000007"),
                            Nome = "Mercearia",
                            Ordem = 6,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("18000000-0000-0000-0000-000000000001"),
                            Nome = "Cimento e Argamassa",
                            Ordem = 0,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("18000000-0000-0000-0000-000000000002"),
                            Nome = "Tijolos e Blocos",
                            Ordem = 1,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("18000000-0000-0000-0000-000000000003"),
                            Nome = "Tintas",
                            Ordem = 2,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("18000000-0000-0000-0000-000000000004"),
                            Nome = "Hidráulica",
                            Ordem = 3,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("18000000-0000-0000-0000-000000000005"),
                            Nome = "Elétrica",
                            Ordem = 4,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("18000000-0000-0000-0000-000000000006"),
                            Nome = "Ferramentas",
                            Ordem = 5,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            TipoTamanho = "letra"
                        },
                        new
                        {
                            Id = new Guid("18000000-0000-0000-0000-000000000007"),
                            Nome = "Madeiras",
                            Ordem = 6,
                            PerfilLojaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            TipoTamanho = "letra"
                        });
                });

            modelBuilder.Entity("LojaApi.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<decimal>("CreditoLoja")
                        .HasColumnType("numeric")
                        .HasColumnName("credito_loja");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("p_k_clientes");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_clientes_loja_id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("LojaApi.Models.ItemTroca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_produto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("TrocaId")
                        .HasColumnType("uuid")
                        .HasColumnName("troca_id");

                    b.Property<Guid?>("VariacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("variacao_id");

                    b.Property<bool>("VoltaEstoque")
                        .HasColumnType("boolean")
                        .HasColumnName("volta_estoque");

                    b.HasKey("Id")
                        .HasName("p_k_itens_troca");

                    b.HasIndex("TrocaId")
                        .HasDatabaseName("i_x_itens_troca_troca_id");

                    b.ToTable("itens_troca");
                });

            modelBuilder.Entity("LojaApi.Models.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_produto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<Guid?>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("quantidade");

                    b.Property<Guid?>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("p_k_itens_venda");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("i_x_itens_venda_produto_id");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("i_x_itens_venda_servico_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("i_x_itens_venda_venda_id");

                    b.ToTable("itens_venda");
                });

            modelBuilder.Entity("LojaApi.Models.Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CorPrimaria")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor_primaria");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<int>("MensalidadeDia")
                        .HasColumnType("integer")
                        .HasColumnName("mensalidade_dia");

                    b.Property<decimal>("MensalidadeValor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("mensalidade_valor");

                    b.Property<int>("MesesPromocional")
                        .HasColumnType("integer")
                        .HasColumnName("meses_promocional");

                    b.Property<string>("ModulosAtivos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("modulos_ativos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("Promocional")
                        .HasColumnType("boolean")
                        .HasColumnName("promocional");

                    b.Property<DateTime?>("ProximoVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proximo_vencimento");

                    b.Property<string>("SchemaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema_nome");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoPlano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_plano");

                    b.Property<DateTime>("TrialAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ate");

                    b.Property<DateTime?>("UltimaCobranca")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_cobranca");

                    b.Property<decimal?>("ValorPosPromocional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_pos_promocional");

                    b.Property<decimal?>("ValorPromocional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_promocional");

                    b.HasKey("Id")
                        .HasName("p_k_lojas");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_lojas_email");

                    b.HasIndex("SchemaNome")
                        .IsUnique()
                        .HasDatabaseName("i_x_lojas_schema_nome");

                    b.ToTable("lojas");
                });

            modelBuilder.Entity("LojaApi.Models.MovimentoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("p_k_movimentos");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_movimentos_loja_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("i_x_movimentos_produto_id");

                    b.ToTable("movimentos");
                });

            modelBuilder.Entity("LojaApi.Models.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("MpBoletoBarcode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mp_boleto_barcode");

                    b.Property<string>("MpBoletoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mp_boleto_url");

                    b.Property<string>("MpPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mp_payment_id");

                    b.Property<string>("MpQrCode")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("mp_qr_code");

                    b.Property<string>("MpQrCodeBase64")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("mp_qr_code_base64");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pago_em");

                    b.Property<Guid?>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vencimento");

                    b.HasKey("Id")
                        .HasName("p_k_pagamentos");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_pagamentos_loja_id");

                    b.ToTable("pagamentos");
                });

            modelBuilder.Entity("LojaApi.Models.PerfilLoja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("p_k_perfis_loja");

                    b.ToTable("perfis_loja");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 7, 1, 20, 4, 47, 662, DateTimeKind.Utc).AddTicks(5793),
                            Descricao = "Para lojas de semi joias, bijuterias e maquiagem",
                            Icone = "💍",
                            Nome = "Semi Joias e Maquiagem"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 7, 1, 20, 4, 47, 662, DateTimeKind.Utc).AddTicks(6008),
                            Descricao = "Para lojas de roupas e moda",
                            Icone = "👕",
                            Nome = "Vestuário"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 7, 1, 20, 4, 47, 662, DateTimeKind.Utc).AddTicks(6142),
                            Descricao = "Para lojas de sapatos, tênis e sandálias",
                            Icone = "👟",
                            Nome = "Calçados"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 7, 1, 20, 4, 47, 662, DateTimeKind.Utc).AddTicks(6239),
                            Descricao = "Para pet shops: ração a granel, petiscos, acessórios e mais",
                            Icone = "🐾",
                            Nome = "Pet Shop"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 7, 1, 20, 4, 47, 662, DateTimeKind.Utc).AddTicks(6308),
                            Descricao = "Para lojas de conveniência, mercadinhos e similares",
                            Icone = "🏪",
                            Nome = "Conveniência"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 7, 1, 20, 4, 47, 662, DateTimeKind.Utc).AddTicks(6381),
                            Descricao = "Para lojas de materiais de construção e ferragens",
                            Icone = "🧱",
                            Nome = "Material de Construção"
                        });
                });

            modelBuilder.Entity("LojaApi.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("categoria");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barras");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("Estoque")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("estoque");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("estoque_minimo");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_custo");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_venda");

                    b.Property<string>("TipoVenda")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo_venda");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id")
                        .HasName("p_k_produtos");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasDatabaseName("i_x_produtos_codigo_barras")
                        .HasFilter("codigo_barras IS NOT NULL");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_produtos_loja_id");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("LojaApi.Models.ProdutoVariacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer")
                        .HasColumnName("estoque");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("OutroCampo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outro_campo");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tamanho");

                    b.HasKey("Id")
                        .HasName("p_k_produto_variacoes");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("i_x_produto_variacoes_produto_id");

                    b.ToTable("produto_variacoes");
                });

            modelBuilder.Entity("LojaApi.Models.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DuracaoMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_min");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id")
                        .HasName("p_k_servicos");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_servicos_loja_id");

                    b.ToTable("servicos");
                });

            modelBuilder.Entity("LojaApi.Models.Troca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("CreditoGerado")
                        .HasColumnType("numeric")
                        .HasColumnName("credito_gerado");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<decimal>("Diferenca")
                        .HasColumnType("numeric")
                        .HasColumnName("diferenca");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<decimal>("TotalDevolvido")
                        .HasColumnType("numeric")
                        .HasColumnName("total_devolvido");

                    b.Property<decimal>("TotalNovo")
                        .HasColumnType("numeric")
                        .HasColumnName("total_novo");

                    b.HasKey("Id")
                        .HasName("p_k_trocas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("i_x_trocas_cliente_id");

                    b.ToTable("trocas");
                });

            modelBuilder.Entity("LojaApi.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("p_k_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_usuarios_email");

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 7, 1, 20, 4, 47, 662, DateTimeKind.Utc).AddTicks(5151),
                            Email = "admin@loja.com",
                            Nome = "Administrador",
                            Role = "admin",
                            SenhaHash = "$2a$11$h8Fk1J7ra51X7Q8GKDmcnOfIp0q/TZR/KpO6xrEjtlDiU3W.ASor."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 7, 1, 20, 4, 47, 662, DateTimeKind.Utc).AddTicks(5719),
                            Email = "superadmin@suaempresa.com",
                            Nome = "Super Admin",
                            Role = "superadmin",
                            SenhaHash = "$2a$11$pJv1QqzqQHz4rG17gLCUoORPXG8/9fS3mtJpTuULzEYV/qc7heetu"
                        });
                });

            modelBuilder.Entity("LojaApi.Models.UsuarioLoja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("p_k_usuarios_loja");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_usuarios_loja_loja_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("i_x_usuarios_loja_usuario_id");

                    b.ToTable("usuarios_loja");
                });

            modelBuilder.Entity("LojaApi.Models.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("desconto");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("FormasPagamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("formas_pagamento");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalFinal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_final");

                    b.Property<decimal?>("Troco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("troco");

                    b.HasKey("Id")
                        .HasName("p_k_vendas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("i_x_vendas_cliente_id");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_vendas_loja_id");

                    b.ToTable("vendas");
                });

            modelBuilder.Entity("LojaApi.Models.Agendamento", b =>
                {
                    b.HasOne("LojaApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_agendamentos__clientes_cliente_id");

                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_agendamentos__lojas_loja_id");

                    b.HasOne("LojaApi.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_agendamentos__servicos_servico_id");

                    b.HasOne("LojaApi.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_agendamentos__vendas_venda_id");

                    b.Navigation("Cliente");

                    b.Navigation("Loja");

                    b.Navigation("Servico");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("LojaApi.Models.CampoExtraLoja", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_campos_extras_loja__lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.CampoExtraPerfil", b =>
                {
                    b.HasOne("LojaApi.Models.PerfilLoja", "PerfilLoja")
                        .WithMany("CamposExtras")
                        .HasForeignKey("PerfilLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_campos_extras_perfil__perfis_loja_perfil_loja_id");

                    b.Navigation("PerfilLoja");
                });

            modelBuilder.Entity("LojaApi.Models.CategoriaLoja", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_categorias_loja__lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.CategoriaPerfilLoja", b =>
                {
                    b.HasOne("LojaApi.Models.PerfilLoja", "PerfilLoja")
                        .WithMany("Categorias")
                        .HasForeignKey("PerfilLojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_categorias_perfil_loja__perfis_loja_perfil_loja_id");

                    b.Navigation("PerfilLoja");
                });

            modelBuilder.Entity("LojaApi.Models.Cliente", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .HasConstraintName("f_k_clientes__lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.ItemTroca", b =>
                {
                    b.HasOne("LojaApi.Models.Troca", "Troca")
                        .WithMany("Itens")
                        .HasForeignKey("TrocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_itens_troca__trocas_troca_id");

                    b.Navigation("Troca");
                });

            modelBuilder.Entity("LojaApi.Models.ItemVenda", b =>
                {
                    b.HasOne("LojaApi.Models.Produto", "Produto")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_itens_venda__produtos_produto_id");

                    b.HasOne("LojaApi.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_itens_venda__servicos_servico_id");

                    b.HasOne("LojaApi.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_itens_venda__vendas_venda_id");

                    b.Navigation("Produto");

                    b.Navigation("Servico");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("LojaApi.Models.MovimentoEstoque", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .HasConstraintName("f_k_movimentos_lojas_loja_id");

                    b.HasOne("LojaApi.Models.Produto", "Produto")
                        .WithMany("Movimentos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_movimentos__produtos_produto_id");

                    b.Navigation("Loja");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaApi.Models.Pagamento", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany("Pagamentos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pagamentos_lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.Produto", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .HasConstraintName("f_k_produtos_lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.ProdutoVariacao", b =>
                {
                    b.HasOne("LojaApi.Models.Produto", "Produto")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_produto_variacoes_produtos_produto_id");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaApi.Models.Servico", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_servicos_lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.Troca", b =>
                {
                    b.HasOne("LojaApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_trocas_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LojaApi.Models.UsuarioLoja", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany("Usuarios")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_usuarios_loja_lojas_loja_id");

                    b.HasOne("LojaApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_usuarios_loja_usuarios_usuario_id");

                    b.Navigation("Loja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LojaApi.Models.Venda", b =>
                {
                    b.HasOne("LojaApi.Models.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_vendas_clientes_cliente_id");

                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .HasConstraintName("f_k_vendas_lojas_loja_id");

                    b.Navigation("Cliente");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("LojaApi.Models.Loja", b =>
                {
                    b.Navigation("Pagamentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LojaApi.Models.PerfilLoja", b =>
                {
                    b.Navigation("CamposExtras");

                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("LojaApi.Models.Produto", b =>
                {
                    b.Navigation("ItensVenda");

                    b.Navigation("Movimentos");

                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("LojaApi.Models.Troca", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("LojaApi.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
