// <auto-generated />
using System;
using LojaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LojaApi.src.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611214859_AddLojaIdToModels")]
    partial class AddLojaIdToModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LojaApi.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("p_k_clientes");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_clientes_loja_id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("LojaApi.Models.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("p_k_itens_venda");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("i_x_itens_venda_produto_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("i_x_itens_venda_venda_id");

                    b.ToTable("itens_venda");
                });

            modelBuilder.Entity("LojaApi.Models.Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CorPrimaria")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor_primaria");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<int>("MensalidadeDia")
                        .HasColumnType("integer")
                        .HasColumnName("mensalidade_dia");

                    b.Property<decimal>("MensalidadeValor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("mensalidade_valor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("ProximoVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proximo_vencimento");

                    b.Property<string>("SchemaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema_nome");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime>("TrialAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ate");

                    b.Property<DateTime?>("UltimaCobranca")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_cobranca");

                    b.HasKey("Id")
                        .HasName("p_k_lojas");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_lojas_email");

                    b.HasIndex("SchemaNome")
                        .IsUnique()
                        .HasDatabaseName("i_x_lojas_schema_nome");

                    b.ToTable("lojas");
                });

            modelBuilder.Entity("LojaApi.Models.MovimentoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("p_k_movimentos");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_movimentos_loja_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("i_x_movimentos_produto_id");

                    b.ToTable("movimentos");
                });

            modelBuilder.Entity("LojaApi.Models.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("MpBoletoBarcode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mp_boleto_barcode");

                    b.Property<string>("MpBoletoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mp_boleto_url");

                    b.Property<string>("MpPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mp_payment_id");

                    b.Property<string>("MpQrCode")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("mp_qr_code");

                    b.Property<string>("MpQrCodeBase64")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("mp_qr_code_base64");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pago_em");

                    b.Property<Guid?>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vencimento");

                    b.HasKey("Id")
                        .HasName("p_k_pagamentos");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_pagamentos_loja_id");

                    b.ToTable("pagamentos");
                });

            modelBuilder.Entity("LojaApi.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("categoria");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barras");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer")
                        .HasColumnName("estoque");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("estoque_minimo");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_custo");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_venda");

                    b.HasKey("Id")
                        .HasName("p_k_produtos");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasDatabaseName("i_x_produtos_codigo_barras")
                        .HasFilter("codigo_barras IS NOT NULL");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_produtos_loja_id");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("LojaApi.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("p_k_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_usuarios_email");

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 11, 21, 48, 58, 846, DateTimeKind.Utc).AddTicks(2828),
                            Email = "admin@loja.com",
                            Nome = "Administrador",
                            Role = "admin",
                            SenhaHash = "$2a$11$thMWsRXhyY0/5BEl3sxsQubav6Aq//pbe89AGfHSC8LrYAxa6Y0Ty"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 6, 11, 21, 48, 58, 846, DateTimeKind.Utc).AddTicks(3508),
                            Email = "superadmin@suaempresa.com",
                            Nome = "Super Admin",
                            Role = "superadmin",
                            SenhaHash = "$2a$11$pJv1QqzqQHz4rG17gLCUoORPXG8/9fS3mtJpTuULzEYV/qc7heetu"
                        });
                });

            modelBuilder.Entity("LojaApi.Models.UsuarioLoja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("p_k_usuarios_loja");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_usuarios_loja_loja_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("i_x_usuarios_loja_usuario_id");

                    b.ToTable("usuarios_loja");
                });

            modelBuilder.Entity("LojaApi.Models.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("desconto");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid")
                        .HasColumnName("loja_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalFinal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_final");

                    b.Property<decimal?>("Troco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("troco");

                    b.HasKey("Id")
                        .HasName("p_k_vendas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("i_x_vendas_cliente_id");

                    b.HasIndex("LojaId")
                        .HasDatabaseName("i_x_vendas_loja_id");

                    b.ToTable("vendas");
                });

            modelBuilder.Entity("LojaApi.Models.Cliente", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .HasConstraintName("f_k_clientes__lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.ItemVenda", b =>
                {
                    b.HasOne("LojaApi.Models.Produto", "Produto")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_itens_venda__produtos_produto_id");

                    b.HasOne("LojaApi.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_itens_venda__vendas_venda_id");

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("LojaApi.Models.MovimentoEstoque", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .HasConstraintName("f_k_movimentos_lojas_loja_id");

                    b.HasOne("LojaApi.Models.Produto", "Produto")
                        .WithMany("Movimentos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_movimentos__produtos_produto_id");

                    b.Navigation("Loja");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaApi.Models.Pagamento", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany("Pagamentos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pagamentos_lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.Produto", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .HasConstraintName("f_k_produtos_lojas_loja_id");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.UsuarioLoja", b =>
                {
                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany("Usuarios")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_usuarios_loja_lojas_loja_id");

                    b.HasOne("LojaApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_usuarios_loja_usuarios_usuario_id");

                    b.Navigation("Loja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LojaApi.Models.Venda", b =>
                {
                    b.HasOne("LojaApi.Models.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_vendas_clientes_cliente_id");

                    b.HasOne("LojaApi.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .HasConstraintName("f_k_vendas_lojas_loja_id");

                    b.Navigation("Cliente");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("LojaApi.Models.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("LojaApi.Models.Loja", b =>
                {
                    b.Navigation("Pagamentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LojaApi.Models.Produto", b =>
                {
                    b.Navigation("ItensVenda");

                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("LojaApi.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
